version: '3'
services:
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
