name: CI

on: [push, pull_request]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build TypeScript and Next.js
        run: yarn build

      - name: Lint files
        run: yarn lint
